# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/___________TD____________/TD_code/core/abcIO/Abc_export.ui'
#
# Created: Sat Dec 15 09:44:36 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 382)
        MainWindow.setMinimumSize(QtCore.QSize(25, 25))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_all = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_all.setEnabled(True)
        self.scrollArea_all.setMinimumSize(QtCore.QSize(1, 1))
        self.scrollArea_all.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea_all.setObjectName("scrollArea_all")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 451, 317))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lin_export_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lin_export_path.setEnabled(False)
        self.lin_export_path.setMinimumSize(QtCore.QSize(0, 25))
        self.lin_export_path.setStyleSheet("border:none")
        self.lin_export_path.setInputMask("")
        self.lin_export_path.setDragEnabled(False)
        self.lin_export_path.setObjectName("lin_export_path")
        self.horizontalLayout_2.addWidget(self.lin_export_path)
        self.btn_sel_path = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_sel_path.setEnabled(False)
        self.btn_sel_path.setMinimumSize(QtCore.QSize(1, 1))
        self.btn_sel_path.setStyleSheet("border:none")
        self.btn_sel_path.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sel_path.setIcon(icon)
        self.btn_sel_path.setIconSize(QtCore.QSize(24, 24))
        self.btn_sel_path.setObjectName("btn_sel_path")
        self.horizontalLayout_2.addWidget(self.btn_sel_path)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 11, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radio_cf = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radio_cf.setObjectName("radio_cf")
        self.verticalLayout_2.addWidget(self.radio_cf)
        self.radio_ts = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radio_ts.setChecked(True)
        self.radio_ts.setObjectName("radio_ts")
        self.verticalLayout_2.addWidget(self.radio_ts)
        self.radio_se = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radio_se.setObjectName("radio_se")
        self.verticalLayout_2.addWidget(self.radio_se)
        self.gridLayout.addLayout(self.verticalLayout_2, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.check_vis_path = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_vis_path.setChecked(True)
        self.check_vis_path.setObjectName("check_vis_path")
        self.gridLayout.addWidget(self.check_vis_path, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.float_start = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.float_start.setEnabled(False)
        self.float_start.setMinimumSize(QtCore.QSize(100, 25))
        self.float_start.setMaximumSize(QtCore.QSize(100, 25))
        self.float_start.setFrame(False)
        self.float_start.setDecimals(4)
        self.float_start.setMinimum(-10000.0)
        self.float_start.setMaximum(10000.0)
        self.float_start.setProperty("value", 1.0)
        self.float_start.setObjectName("float_start")
        self.horizontalLayout_3.addWidget(self.float_start)
        self.float_end = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.float_end.setEnabled(False)
        self.float_end.setMinimumSize(QtCore.QSize(100, 25))
        self.float_end.setMaximumSize(QtCore.QSize(100, 25))
        self.float_end.setFrame(False)
        self.float_end.setDecimals(4)
        self.float_end.setMinimum(-10000.0)
        self.float_end.setMaximum(10000.0)
        self.float_end.setProperty("value", 1.0)
        self.float_end.setObjectName("float_end")
        self.horizontalLayout_3.addWidget(self.float_end)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 1, 1, 1)
        self.float_step = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.float_step.setMinimumSize(QtCore.QSize(100, 25))
        self.float_step.setMaximumSize(QtCore.QSize(100, 25))
        self.float_step.setFrame(False)
        self.float_step.setDecimals(4)
        self.float_step.setMinimum(0.0)
        self.float_step.setMaximum(10.0)
        self.float_step.setSingleStep(0.1)
        self.float_step.setProperty("value", 1.0)
        self.float_step.setObjectName("float_step")
        self.gridLayout.addWidget(self.float_step, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 1000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 1, 1, 1)
        self.check_cam = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_cam.setChecked(True)
        self.check_cam.setObjectName("check_cam")
        self.gridLayout.addWidget(self.check_cam, 11, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.check_body = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_body.setChecked(True)
        self.check_body.setObjectName("check_body")
        self.gridLayout_2.addWidget(self.check_body, 1, 0, 1, 1)
        self.check_prop = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_prop.setChecked(True)
        self.check_prop.setObjectName("check_prop")
        self.gridLayout_2.addWidget(self.check_prop, 4, 0, 1, 1)
        self.check_BG = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_BG.setChecked(True)
        self.check_BG.setObjectName("check_BG")
        self.gridLayout_2.addWidget(self.check_BG, 3, 0, 1, 1)
        self.check_color_set = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_color_set.setChecked(True)
        self.check_color_set.setObjectName("check_color_set")
        self.gridLayout_2.addWidget(self.check_color_set, 2, 0, 1, 1)
        self.check_export_sel = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_export_sel.setEnabled(True)
        self.check_export_sel.setChecked(False)
        self.check_export_sel.setObjectName("check_export_sel")
        self.gridLayout_2.addWidget(self.check_export_sel, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 12, 1, 1, 1)
        self.scrollArea_all.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea_all)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cjjc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cjjc.setObjectName("btn_cjjc")
        self.horizontalLayout.addWidget(self.btn_cjjc)
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.check_vis_path, QtCore.SIGNAL("toggled(bool)"), self.lin_export_path.setDisabled)
        QtCore.QObject.connect(self.check_vis_path, QtCore.SIGNAL("toggled(bool)"), self.btn_sel_path.setDisabled)
        QtCore.QObject.connect(self.radio_se, QtCore.SIGNAL("toggled(bool)"), self.float_start.setEnabled)
        QtCore.QObject.connect(self.radio_se, QtCore.SIGNAL("toggled(bool)"), self.float_end.setEnabled)
        QtCore.QObject.connect(self.btn_cancel, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.check_export_sel, QtCore.SIGNAL("toggled(bool)"), self.check_body.setDisabled)
        QtCore.QObject.connect(self.check_export_sel, QtCore.SIGNAL("toggled(bool)"), self.check_color_set.setDisabled)
        QtCore.QObject.connect(self.check_export_sel, QtCore.SIGNAL("toggled(bool)"), self.check_BG.setDisabled)
        QtCore.QObject.connect(self.check_export_sel, QtCore.SIGNAL("toggled(bool)"), self.check_prop.setDisabled)
        QtCore.QObject.connect(self.check_export_sel, QtCore.SIGNAL("toggled(bool)"), self.check_cam.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "ABC IO", None, -1))
        self.lin_export_path.setText(QtWidgets.QApplication.translate("MainWindow", "D:/Repo", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">导出选项：</p></body></html>", None, -1))
        self.radio_cf.setText(QtWidgets.QApplication.translate("MainWindow", "Current frame", None, -1))
        self.radio_ts.setText(QtWidgets.QApplication.translate("MainWindow", "Time Slider", None, -1))
        self.radio_se.setText(QtWidgets.QApplication.translate("MainWindow", "Start/End", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">Start/End</p></body></html>", None, -1))
        self.check_vis_path.setText(QtWidgets.QApplication.translate("MainWindow", "自动匹配相机路径", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">输出路径：</p></body></html>", None, -1))
        self.check_cam.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>导出相机是 FBX 格式</p></body></html>", None, -1))
        self.check_cam.setText(QtWidgets.QApplication.translate("MainWindow", "相机", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">Step：</p></body></html>", None, -1))
        self.check_body.setText(QtWidgets.QApplication.translate("MainWindow", "人物", None, -1))
        self.check_prop.setText(QtWidgets.QApplication.translate("MainWindow", "道具", None, -1))
        self.check_BG.setText(QtWidgets.QApplication.translate("MainWindow", "BG", None, -1))
        self.check_color_set.setText(QtWidgets.QApplication.translate("MainWindow", "面部颜色集", None, -1))
        self.check_export_sel.setText(QtWidgets.QApplication.translate("MainWindow", "选择导出", None, -1))
        self.btn_cjjc.setText(QtWidgets.QApplication.translate("MainWindow", "场景检测", None, -1))
        self.btn_export.setText(QtWidgets.QApplication.translate("MainWindow", "Export", None, -1))
        self.btn_cancel.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))

